#!/usr/bin/perl

@data = ();

$min = 1 << 30;
$max = - $min;
$sum = 0;
$sumsq = 0;
$count = 0;

while (<>) {
    $value = int($_);
    push(@data, $value);
    $min = $value if $value < $min;
    $max = $value if $value > $max;
    $sum += $value;
    $sumsq += $value * $value;
    $count++;
}

$mean = $sum / $count;
@data = sort {$a <=> $b} @data;
$median = $data[$#data/2];
$stddev = sqrt($sumsq/$count - $mean**2);

print <<end;
min = $min
max = $max
mean = $mean
median = $median
stddev = $stddev
end


