#!/bin/sh
#
# The test suite uses m4 to emit a shell script that verifies sample
# command output against expected results on stdout and stderr.

cd $(dirname $0)

export ONLY="$1"
PATH=.:$PATH

(
m4 -P <<\!
(

m4_changequote(`<<', `>>')

cleanup() {
    rm -f t_std{out,err}_{expected,actual}
    rm -f t.? t.?.Z t.?.gz
}

trap cleanup 0
nfailures=0

# The 'test' macro has five arguments:
#   test name
#   command line
#   stdin
#   expected stdout
#   expected stderr

m4_define(<<test>>, <<
if [ "" = "$ONLY" -o "$1" = "$ONLY" ]; then
    echo '$4\c' | sed 1d >t_stdout_expected
    echo '$5\c' | sed 1d >t_stderr_expected
    echo '$3\c' | sed 1d | ./tl $2 >t_stdout_actual 2>t_stderr_actual
    if [[ "$(cksum < t_stdout_actual)" != "$(cksum < t_stdout_expected)" ]]; then
        echo "Test '$1' failed, stdouts differ"
        diff t_stdout_expected t_stdout_actual
        nfailures=$(( $nfailures + 1 ))
    fi
    if [[ "$(cksum < t_stderr_actual)" != "$(cksum < t_stderr_expected)" ]]; then
        echo "Test '$1' failed, stderrs differ"
        diff t_stderr_expected t_stderr_actual
        nfailures=$(( $nfailures + 1 ))
    fi
fi
>>)

m4_include(<<tests/inputs.m4>>)

m4_include(<<tests/sep.m4>>)
m4_include(<<tests/keep.m4>>)
m4_include(<<tests/drop.m4>>)
m4_include(<<tests/ord.m4>>)
m4_include(<<tests/per.m4>>)
m4_include(<<tests/cum.m4>>)
m4_include(<<tests/format.m4>>)
m4_include(<<tests/delta.m4>>)
m4_include(<<tests/dup.m4>>)
m4_include(<<tests/sub.m4>>)
m4_include(<<tests/round.m4>>)
m4_include(<<tests/set.m4>>)
m4_include(<<tests/add.m4>>)

if [[ $nfailures > 0 ]]; then
    exit 1
else
    exit 0
fi

)
!
) | sh

